name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: npm test
        run: pnpm test -- --coverage

      - name: Publish to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


